
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: figure1
    tier: backend
    role: elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: figure1
    tier: backend
    role: elasticsearch

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: figure1
      tier: backend
      role: elasticsearch
  template:
    metadata:
      labels:
        app: figure1
        tier: backend
        role: elasticsearch
    spec:
      containers:
        - name: es-1
          image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: figure1-es-volume
          resources:
            requests:
              cpu: 100m                                  # requests a minimum of 1/10th of a CPU (may use more)
              memory: 2000Mi                              # requests a minimum of 100MB of memory (may use more)
          ports:
            - containerPort: 9200
      volumes:
        - name: figure1-es-volume
          hostPath:
            # dev/start-dev.sh creates a symlink to <project root>/database so that /figure1/database always works
            path: /private/figure1-es
            type: DirectoryOrCreate