version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: figure1_admin
      POSTGRES_DB: figure1_test
      POSTGRES_PASSWORD: test1234
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
  redis-slave:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
  redis-sentinel-1:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_SET=redismaster
    depends_on:
      - redis
      - redis-slave
  redis-sentinel-2:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_SET=redismaster
    depends_on:
      - redis
      - redis-slave
  redis-sentinel-3:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_SET=redismaster
    depends_on:
      - redis
      - redis-slave
  firestore:
    image: mtlynch/firestore-emulator
    environment:
      PORT: "8200"
      FIRESTORE_PROJECT_ID: some-project-id
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      discovery.type: single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      start_period: 5s
      retries: 5
      timeout: 3s
      interval: 10s
    ports:
      - 9200
  figure1:
    build:
      context: .
    environment:
      DATABASE_DSN: "postgresql://figure1_admin:test1234@postgres:5432/figure1_test"
      REDIS_URL: 'sentinel://redis-sentinel-3:26379/0;sentinel://_redis-sentinel-2:26379/0;sentinel://redis-sentinel-1:26379/0'
      FIRESTORE_EMULATOR_HOST: firestore:8200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SENTINEL_ENABLED: "true"
    command: python -m pytest figure1/tests -vvvv --showlocals
    depends_on:
      - elasticsearch
      - postgres
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
      - firestore