[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-sqlalchemy_utils]
ignore_missing_imports = True

[mypy-flask_jwt_extended]
ignore_missing_imports = True

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-elasticsearch.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-firebase_admin.*]
ignore_missing_imports = True

[mypy-kombu]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-pytest]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-fuzzywuzzy.*]
ignore_missing_imports = True

[mypy-bson.*]
ignore_missing_imports = True

[mypy-pycountry.*]
ignore_missing_imports = True

[mypy-pymongo.*]
ignore_missing_imports = True

[mypy-sortedcontainers.*]
ignore_missing_imports = True

[mypy-pythonjsonlogger.*]
ignore_missing_imports = True