"""adding two tables for blocked usernames

Revision ID: 5517a82459b0
Revises: 0211f8580453
Create Date: 2021-08-16 14:07:55.778421

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5517a82459b0'
down_revision = '0211f8580453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_forbidden_usernames',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forbidden_usernames', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('forbidden_usernames', name=op.f('pk_r_forbidden_usernames'))
    )
    op.create_index(op.f('ix_r_forbidden_usernames_created_at'), 'r_forbidden_usernames', ['created_at'], unique=False)
    op.create_index(op.f('ix_r_forbidden_usernames_deleted_at'), 'r_forbidden_usernames', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_r_forbidden_usernames_forbidden_usernames'), 'r_forbidden_usernames', ['forbidden_usernames'], unique=False)
    op.create_index(op.f('ix_r_forbidden_usernames_updated_at'), 'r_forbidden_usernames', ['updated_at'], unique=False)
    op.create_table('r_less_forbidden_usernames',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('less_forbidden_usernames', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('less_forbidden_usernames', name=op.f('pk_r_less_forbidden_usernames'))
    )
    op.create_index(op.f('ix_r_less_forbidden_usernames_created_at'), 'r_less_forbidden_usernames', ['created_at'], unique=False)
    op.create_index(op.f('ix_r_less_forbidden_usernames_deleted_at'), 'r_less_forbidden_usernames', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_r_less_forbidden_usernames_less_forbidden_usernames'), 'r_less_forbidden_usernames', ['less_forbidden_usernames'], unique=False)
    op.create_index(op.f('ix_r_less_forbidden_usernames_updated_at'), 'r_less_forbidden_usernames', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_r_less_forbidden_usernames_updated_at'), table_name='r_less_forbidden_usernames')
    op.drop_index(op.f('ix_r_less_forbidden_usernames_less_forbidden_usernames'), table_name='r_less_forbidden_usernames')
    op.drop_index(op.f('ix_r_less_forbidden_usernames_deleted_at'), table_name='r_less_forbidden_usernames')
    op.drop_index(op.f('ix_r_less_forbidden_usernames_created_at'), table_name='r_less_forbidden_usernames')
    op.drop_table('r_less_forbidden_usernames')
    op.drop_index(op.f('ix_r_forbidden_usernames_updated_at'), table_name='r_forbidden_usernames')
    op.drop_index(op.f('ix_r_forbidden_usernames_forbidden_usernames'), table_name='r_forbidden_usernames')
    op.drop_index(op.f('ix_r_forbidden_usernames_deleted_at'), table_name='r_forbidden_usernames')
    op.drop_index(op.f('ix_r_forbidden_usernames_created_at'), table_name='r_forbidden_usernames')
    op.drop_table('r_forbidden_usernames')
    # ### end Alembic commands ###
