"""Add recommended case table

Revision ID: e38da52b6071
Revises: 01b1fffb3cab
Create Date: 2021-10-22 15:35:59.602868

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e38da52b6071'
down_revision = '01b1fffb3cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_user_recommended_case',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('case_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['case_uuid'], ['c_case.case_uuid'], name=op.f('fk_u_user_recommended_case_case_uuid_c_case')),
    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'], name=op.f('fk_u_user_recommended_case_user_uuid_u_user')),
    sa.PrimaryKeyConstraint('user_uuid', 'case_uuid', name=op.f('pk_u_user_recommended_case'))
    )
    op.create_index(op.f('ix_u_user_recommended_case_created_at'), 'u_user_recommended_case', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_user_recommended_case_deleted_at'), 'u_user_recommended_case', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_u_user_recommended_case_updated_at'), 'u_user_recommended_case', ['updated_at'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_user_recommended_case_updated_at'), table_name='u_user_recommended_case')
    op.drop_index(op.f('ix_u_user_recommended_case_deleted_at'), table_name='u_user_recommended_case')
    op.drop_index(op.f('ix_u_user_recommended_case_created_at'), table_name='u_user_recommended_case')
    op.drop_table('u_user_recommended_case')
    # ### end Alembic commands ###
