"""add flag for review and verification history table

Revision ID: e1ee58bc0794
Revises: fe72a4a557a0
Create Date: 2021-05-13 08:59:07.712989

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1ee58bc0794'
down_revision = 'fe72a4a557a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_verification_history',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_event_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('verification_record_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('verification_event_initiator', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('verification_event_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['verification_event_initiator'], ['u_user.user_uuid'], name=op.f('fk_h_verification_history_verification_event_initiator_u_user')),
    sa.ForeignKeyConstraint(['verification_record_uuid'], ['u_user_verification.verification_uuid'], name=op.f('fk_h_verification_history_verification_record_uuid_u_user_verification')),
    sa.PrimaryKeyConstraint('verification_event_uuid', name=op.f('pk_h_verification_history'))
    )
    op.create_index(op.f('ix_h_verification_history_created_at'), 'h_verification_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_h_verification_history_updated_at'), 'h_verification_history', ['updated_at'], unique=False)
    op.create_index(op.f('ix_h_verification_history_verification_event_initiator'), 'h_verification_history', ['verification_event_initiator'], unique=False)
    op.create_index(op.f('ix_h_verification_history_verification_record_uuid'), 'h_verification_history', ['verification_record_uuid'], unique=False)
    op.add_column('u_user_verification', sa.Column('flagged_for_review', sa.Boolean(), nullable=True))
    op.add_column('u_user_verification', sa.Column('last_modified_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_u_user_verification_last_modified_by'), 'u_user_verification', ['last_modified_by'], unique=False)
    op.create_foreign_key(op.f('fk_u_user_verification_last_modified_by_u_user'), 'u_user_verification', 'u_user', ['last_modified_by'], ['user_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_u_user_verification_last_modified_by_u_user'), 'u_user_verification', type_='foreignkey')
    op.drop_index(op.f('ix_u_user_verification_last_modified_by'), table_name='u_user_verification')
    op.drop_column('u_user_verification', 'last_modified_by')
    op.drop_column('u_user_verification', 'flagged_for_review')
    op.drop_index(op.f('ix_h_verification_history_verification_record_uuid'), table_name='h_verification_history')
    op.drop_index(op.f('ix_h_verification_history_verification_event_initiator'), table_name='h_verification_history')
    op.drop_index(op.f('ix_h_verification_history_updated_at'), table_name='h_verification_history')
    op.drop_index(op.f('ix_h_verification_history_created_at'), table_name='h_verification_history')
    op.drop_table('h_verification_history')
    # ### end Alembic commands ###
