"""update content comment counts

Revision ID: 9c3965bcccdd
Revises: ac6cbacd3363
Create Date: 2021-05-25 19:54:43.297909

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c3965bcccdd'
down_revision = 'ac6cbacd3363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""with update_content as (
        select content_uuid,
               count(content_uuid) as c_content_count
        from c_comment where state = 'APPROVED'
        group by content_uuid
        order by c_content_count desc
        )  UPDATE c_content set approved_comments_count=(SELECT update_content.c_content_count
        from update_content where c_content.content_uuid = update_content.content_uuid)
        from update_content where update_content.content_uuid = c_content.content_uuid 
        and approved_comments_count is null""")

    op.execute("""update c_content set approved_comments_count = 0 where approved_comments_count is null""")
    #

def downgrade():
    ### Rollback not relevant here ###
    pass
    ### end Alembic commands ###
