"""add channel type comm method

Revision ID: ef7bbb688cac
Revises: 9d3dfcefe2f0
Create Date: 2021-10-04 12:05:43.243759

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef7bbb688cac'
down_revision = '9d3dfcefe2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'communicationmethods', ['EMAIL', 'PUSH', 'SMS'], ['CHANNEL', 'EMAIL', 'PUSH', 'SMS'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'communicationmethods', ['CHANNEL', 'EMAIL', 'PUSH', 'SMS'], ['EMAIL', 'PUSH', 'SMS'])
    # ### end Alembic commands ###
