"""create user state table

Revision ID: ab476aa5bda6
Revises: d24fe68b836b
Create Date: 2021-04-27 15:49:49.507279

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab476aa5bda6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_user_state',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_interests_completed', sa.Boolean(), nullable=True),
    sa.Column('hidden_from_iterable', sa.Boolean(), nullable=True),
    sa.Column('hidden_from_search', sa.Boolean(), nullable=True),
    sa.Column('sponsored_content_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_synced_activity', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'], name=op.f('fk_u_user_state_user_uuid_u_user')),
    sa.PrimaryKeyConstraint('user_uuid', name=op.f('pk_u_user_state'))
    )
    op.create_index(op.f('ix_u_user_state_created_at'), 'u_user_state', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_user_state_deleted_at'), 'u_user_state', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_u_user_state_updated_at'), 'u_user_state', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_user_state_updated_at'), table_name='u_user_state')
    op.drop_index(op.f('ix_u_user_state_deleted_at'), table_name='u_user_state')
    op.drop_index(op.f('ix_u_user_state_created_at'), table_name='u_user_state')
    op.drop_table('u_user_state')
    # ### end Alembic commands ###
