"""user scheduled aggregations

Revision ID: 0211f8580453
Revises: 44f9b1146037
Create Date: 2021-08-09 16:09:33.862063

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0211f8580453'
down_revision = '44f9b1146037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_user_scheduled_aggregations',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_schedule', sa.String(), nullable=False),
    sa.Column('last_run_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'], name=op.f('fk_u_user_scheduled_aggregations_user_uuid_u_user')),
    sa.PrimaryKeyConstraint('user_uuid', 'event_name', name=op.f('pk_u_user_scheduled_aggregations'))
    )
    op.create_index(op.f('ix_u_user_scheduled_aggregations_created_at'), 'u_user_scheduled_aggregations', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_user_scheduled_aggregations_deleted_at'), 'u_user_scheduled_aggregations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_u_user_scheduled_aggregations_updated_at'), 'u_user_scheduled_aggregations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_user_scheduled_aggregations_updated_at'), table_name='u_user_scheduled_aggregations')
    op.drop_index(op.f('ix_u_user_scheduled_aggregations_deleted_at'), table_name='u_user_scheduled_aggregations')
    op.drop_index(op.f('ix_u_user_scheduled_aggregations_created_at'), table_name='u_user_scheduled_aggregations')
    op.drop_table('u_user_scheduled_aggregations')
    # ### end Alembic commands ###
