"""Add group tables

Revision ID: 969d45b0dd70
Revises: 6b1ec2d47c02
Create Date: 2021-12-20 13:52:03.982365

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '969d45b0dd70'
down_revision = '6b1ec2d47c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('g_groups',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('group_name', sa.String(), nullable=False),
                    sa.Column('group_label', sa.String(), nullable=False),
                    sa.Column('group_description', sa.String(), nullable=True),
                    sa.Column('group_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('group_uuid', name=op.f('pk_g_groups'))
                    )
    op.create_index(op.f('ix_g_groups_created_at'), 'g_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_g_groups_deleted_at'), 'g_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_g_groups_updated_at'), 'g_groups', ['updated_at'], unique=False)
    op.create_table('g_group_member_filter',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('group_filter_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('user_first_name', sa.String(), nullable=True),
                    sa.Column('user_last_name', sa.String(), nullable=True),
                    sa.Column('user_email', sa.String(), nullable=True),
                    sa.Column('user_npi', sa.Integer(), nullable=True),
                    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['group_uuid'], ['g_groups.group_uuid'],
                                            name=op.f('fk_g_group_member_filter_group_uuid_g_groups')),
                    sa.PrimaryKeyConstraint('group_filter_uuid', name=op.f('pk_g_group_member_filter'))
                    )
    op.create_index(op.f('ix_g_group_member_filter_created_at'), 'g_group_member_filter', ['created_at'], unique=False)
    op.create_index(op.f('ix_g_group_member_filter_deleted_at'), 'g_group_member_filter', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_g_group_member_filter_updated_at'), 'g_group_member_filter', ['updated_at'], unique=False)
    op.create_table('g_group_members',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['group_uuid'], ['g_groups.group_uuid'],
                                            name=op.f('fk_g_group_members_group_uuid_g_groups')),
                    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'],
                                            name=op.f('fk_g_group_members_user_uuid_u_user')),
                    sa.PrimaryKeyConstraint('user_uuid', 'group_uuid', name=op.f('pk_g_group_members'))
                    )
    op.create_index(op.f('ix_g_group_members_created_at'), 'g_group_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_g_group_members_deleted_at'), 'g_group_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_g_group_members_updated_at'), 'g_group_members', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_g_group_members_updated_at'), table_name='g_group_members')
    op.drop_index(op.f('ix_g_group_members_deleted_at'), table_name='g_group_members')
    op.drop_index(op.f('ix_g_group_members_created_at'), table_name='g_group_members')
    op.drop_table('g_group_members')
    op.drop_index(op.f('ix_g_group_member_filter_updated_at'), table_name='g_group_member_filter')
    op.drop_index(op.f('ix_g_group_member_filter_deleted_at'), table_name='g_group_member_filter')
    op.drop_index(op.f('ix_g_group_member_filter_created_at'), table_name='g_group_member_filter')
    op.drop_table('g_group_member_filter')
    op.drop_index(op.f('ix_g_groups_updated_at'), table_name='g_groups')
    op.drop_index(op.f('ix_g_groups_deleted_at'), table_name='g_groups')
    op.drop_index(op.f('ix_g_groups_created_at'), table_name='g_groups')
    op.drop_table('g_groups')
    # ### end Alembic commands ###
