"""drop deprecated user specialty tree and user interest tables

Revision ID: 9d3dfcefe2f0
Revises: 2637cfcf1134
Create Date: 2021-10-04 09:53:45.093424

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d3dfcefe2f0'
down_revision = '2637cfcf1134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_u_user_interests_tree_created_at', table_name='u_user_interests_tree')
    op.drop_index('ix_u_user_interests_tree_deleted_at', table_name='u_user_interests_tree')
    op.drop_index('ix_u_user_interests_tree_updated_at', table_name='u_user_interests_tree')
    op.drop_table('u_user_interests_tree')
    op.drop_index('ix_u_user_specialty_tree_created_at', table_name='u_user_specialty_tree')
    op.drop_index('ix_u_user_specialty_tree_deleted_at', table_name='u_user_specialty_tree')
    op.drop_index('ix_u_user_specialty_tree_updated_at', table_name='u_user_specialty_tree')
    op.drop_table('u_user_specialty_tree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_user_specialty_tree',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('tree_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tree_uuid'], ['r_specialty_tree.tree_uuid'], name='fk_u_user_specialty_tree_tree_uuid_r_specialty_tree'),
    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'], name='fk_u_user_specialty_tree_user_uuid_u_user'),
    sa.PrimaryKeyConstraint('user_uuid', 'tree_uuid', name='pk_u_user_specialty_tree')
    )
    op.create_index('ix_u_user_specialty_tree_updated_at', 'u_user_specialty_tree', ['updated_at'], unique=False)
    op.create_index('ix_u_user_specialty_tree_deleted_at', 'u_user_specialty_tree', ['deleted_at'], unique=False)
    op.create_index('ix_u_user_specialty_tree_created_at', 'u_user_specialty_tree', ['created_at'], unique=False)
    op.create_table('u_user_interests_tree',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('tree_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tree_uuid'], ['r_specialty_tree.tree_uuid'], name='fk_u_user_interests_tree_tree_uuid_r_specialty_tree'),
    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'], name='fk_u_user_interests_tree_user_uuid_u_user'),
    sa.PrimaryKeyConstraint('user_uuid', 'tree_uuid', name='pk_u_user_interests_tree')
    )
    op.create_index('ix_u_user_interests_tree_updated_at', 'u_user_interests_tree', ['updated_at'], unique=False)
    op.create_index('ix_u_user_interests_tree_deleted_at', 'u_user_interests_tree', ['deleted_at'], unique=False)
    op.create_index('ix_u_user_interests_tree_created_at', 'u_user_interests_tree', ['created_at'], unique=False)
    # ### end Alembic commands ###
