"""adding columns to the media table

 Revision ID: e5642765723f
Revises: 4c16469e4fdf
Create Date: 2021-11-16 13:57:34.088187

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5642765723f'
down_revision = '4c16469e4fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('c_media', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('c_media', sa.Column('filename_exists', sa.Boolean(), nullable=True))
    op.add_column('c_media', sa.Column('original_filename_exists', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('c_media', 'original_filename_exists')
    op.drop_column('c_media', 'filename_exists')
    op.drop_column('c_media', 'checked_at')

    # ### end Alembic commands ###
