"""Anonymous User table

Revision ID: b3cef691d9c7
Revises: 4919005446db
Create Date: 2021-07-07 14:27:41.582656

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3cef691d9c7'
down_revision = '4919005446db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_anonymous_user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('user_uid', sa.Text(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.PrimaryKeyConstraint('user_uid', name=op.f('pk_u_anonymous_user'))
    )
    op.create_index(op.f('ix_u_anonymous_user_created_at'), 'u_anonymous_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_anonymous_user_deleted_at'), 'u_anonymous_user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_u_anonymous_user_email'), 'u_anonymous_user', ['email'], unique=False)
    op.create_index(op.f('ix_u_anonymous_user_updated_at'), 'u_anonymous_user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_u_anonymous_user_user_uid'), 'u_anonymous_user', ['user_uid'], unique=True)

    op.drop_constraint('fk_c_question_vote_user_uuid_u_user', 'c_question_vote', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key('fk_c_question_vote_user_uuid_u_user', 'c_question_vote', 'u_user', ['user_uuid'], ['user_uuid'])

    op.drop_index(op.f('ix_u_anonymous_user_user_uid'), table_name='u_anonymous_user')
    op.drop_index(op.f('ix_u_anonymous_user_updated_at'), table_name='u_anonymous_user')
    op.drop_index(op.f('ix_u_anonymous_user_email'), table_name='u_anonymous_user')
    op.drop_index(op.f('ix_u_anonymous_user_deleted_at'), table_name='u_anonymous_user')
    op.drop_index(op.f('ix_u_anonymous_user_created_at'), table_name='u_anonymous_user')
    op.drop_table('u_anonymous_user')
    # ### end Alembic commands ###
