"""add follow count

Revision ID: 7a4745a077ff
Revises: 29de4a2736f3
Create Date: 2021-07-14 10:21:55.254298

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a4745a077ff'
down_revision = '29de4a2736f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('u_user', sa.Column('user_follower_count', sa.Integer(), nullable=True))
    op.add_column('u_user', sa.Column('user_following_count', sa.Integer(), nullable=True))
    ### This only hits the top 100 because running the whole table is very heavy. Any change to following or followers
    ### updates the row in users. The full update can be run once then everything should stay up to date.
    op.execute("""
with user_followers as (
select uuf.user_uuid as usuuid, count(uuf.follower_uuid) as user_follower_count
from u_user_follow uuf
where uuf.deleted_at is null
group by uuf.user_uuid order by user_follower_count desc
    limit 100
) update u_user set user_follower_count=(select user_follower_count from user_followers where user_followers.usuuid = u_user.user_uuid)
from user_followers where user_uuid = usuuid;

with user_following as (
    select uuf.follower_uuid as followuuid, count(uuf.follower_uuid) as user_following_count
from u_user_follow uuf
where uuf.deleted_at is null
group by uuf.follower_uuid order by user_following_count desc
    limit 100
) update u_user set user_following_count=(select user_following_count from user_following where user_following.followuuid = u_user.user_uuid) from user_following
where user_uuid = followuuid;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('u_user', 'user_following_count')
    op.drop_column('u_user', 'user_follower_count')

    # ### end Alembic commands ###
