""" make caption nullable

Revision ID: d14318db66c4
Revises: 6c74440afacc
Create Date: 2021-06-15 17:38:09.665727

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd14318db66c4'
down_revision = '6c74440afacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('c_content', 'caption',
               existing_type=sa.VARCHAR(length=100000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('c_content', 'caption',
               existing_type=sa.VARCHAR(length=100000),
               nullable=False)
    # ### end Alembic commands ###
