"""add follower index

Revision ID: 2ec5d74a1c81
Revises: 7a4745a077ff
Create Date: 2021-07-20 14:09:42.578682

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ec5d74a1c81'
down_revision = '7a4745a077ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('ix_u_user_follow_follower', 'u_user_follow', ['user_uuid', 'follower_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_u_user_follow_follower', table_name='u_user_follow')
    # ### end Alembic commands ###
