"""Add two enum values

Revision ID: 2637cfcf1134
Revises: e773a6cb68b5
Create Date: 2021-09-21 15:07:58.819007

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2637cfcf1134'
down_revision = 'e773a6cb68b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.sync_enum_values('public', 'communicationtypes', ['ACTIVITY', 'CONTENT', 'TRANSACTIONAL'], ['ACTIVITY', 'CHANNEL', 'CONTENT', 'TRANSACTIONAL'])
    op.sync_enum_values('public', 'feedcardtype', ['BASIC', 'END_OF_FEED', 'HIGHLIGHT'], ['BASIC', 'END_OF_FEED', 'HIGHLIGHT', 'PREVIEW_FEED'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'feedcardtype', ['BASIC', 'END_OF_FEED', 'HIGHLIGHT', 'PREVIEW_FEED'], ['BASIC', 'END_OF_FEED', 'HIGHLIGHT'])
    op.sync_enum_values('public', 'communicationtypes', ['ACTIVITY', 'CHANNEL', 'CONTENT', 'TRANSACTIONAL'], ['ACTIVITY', 'CONTENT', 'TRANSACTIONAL'])
    # ### end Alembic commands ###
