"""add activity sync state flag

Revision ID: 100c648c16ba
Revises: 10c2b19bb908
Create Date: 2021-05-20 20:33:29.494540

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100c648c16ba'
down_revision = '10c2b19bb908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_user_state', sa.Column('activity_sync_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('u_user_state', 'activity_sync_complete')
    # ### end Alembic commands ###
