"""add comment history table and comment_count tracking

Revision ID: 5cbfb1fb9590
Revises: 09e5d9d85058
Create Date: 2021-05-14 15:17:30.910150

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cbfb1fb9590'
down_revision = '09e5d9d85058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_comment_history',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_author', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_reported_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_approved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_reviewed_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_report_record', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment_state', sa.Text(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_report_text', sa.Text(), nullable=True),
    sa.Column('comment_report_reason', sa.Text(), nullable=True),
    sa.Column('comment_history_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comment_approved_by'], ['u_user.user_uuid'], name=op.f('fk_h_comment_history_comment_approved_by_u_user')),
    sa.ForeignKeyConstraint(['comment_author'], ['u_user.user_uuid'], name=op.f('fk_h_comment_history_comment_author_u_user')),
    sa.ForeignKeyConstraint(['comment_report_record'], ['c_comment_report.comment_report_uuid'], name=op.f('fk_h_comment_history_comment_report_record_c_comment_report')),
    sa.ForeignKeyConstraint(['comment_reported_by'], ['u_user.user_uuid'], name=op.f('fk_h_comment_history_comment_reported_by_u_user')),
    sa.ForeignKeyConstraint(['comment_reviewed_by'], ['u_user.user_uuid'], name=op.f('fk_h_comment_history_comment_reviewed_by_u_user')),
    sa.ForeignKeyConstraint(['comment_uuid'], ['c_comment.comment_uuid'], name=op.f('fk_h_comment_history_comment_uuid_c_comment')),
    sa.ForeignKeyConstraint(['event_author'], ['u_user.user_uuid'], name=op.f('fk_h_comment_history_event_author_u_user')),
    sa.PrimaryKeyConstraint('event_uuid', name=op.f('pk_h_comment_history'))
    )
    op.create_index(op.f('ix_h_comment_history_comment_author'), 'h_comment_history', ['comment_author'], unique=False)
    op.create_index(op.f('ix_h_comment_history_comment_uuid'), 'h_comment_history', ['comment_uuid'], unique=False)
    op.create_index(op.f('ix_h_comment_history_created_at'), 'h_comment_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_h_comment_history_deleted_at'), 'h_comment_history', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_h_comment_history_event_author'), 'h_comment_history', ['event_author'], unique=False)
    op.create_index(op.f('ix_h_comment_history_updated_at'), 'h_comment_history', ['updated_at'], unique=False)

    op.add_column('u_user', sa.Column('approved_comment_count', sa.Integer(), nullable=True))
    op.add_column('u_user', sa.Column('deleted_comment_count', sa.Integer(), nullable=True))
    op.add_column('u_user', sa.Column('last_posted_comment', sa.DateTime(), nullable=True))
    op.add_column('u_user', sa.Column('reported_comment_count', sa.Integer(), nullable=True))

    op.drop_column('u_user_state', 'case_reported_count')
    op.drop_column('u_user_state', 'last_comment')
    op.drop_column('u_user_state', 'comment_authored_count')
    op.drop_column('u_user_state', 'comment_deleted_count')
    op.drop_column('u_user_state', 'case_uploaded_count')
    op.drop_column('u_user_state', 'comment_reports_count')
    op.drop_column('u_user_state', 'last_case_upload')
    op.drop_column('u_user_state', 'comment_reported_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_user_state', sa.Column('comment_reported_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('last_case_upload', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('comment_reports_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('case_uploaded_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('comment_deleted_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('comment_authored_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('last_comment', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('u_user_state', sa.Column('case_reported_count', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_column('u_user', 'reported_comment_count')
    op.drop_column('u_user', 'last_posted_comment')
    op.drop_column('u_user', 'deleted_comment_count')
    op.drop_column('u_user', 'approved_comment_count')

    op.drop_index(op.f('ix_h_comment_history_updated_at'), table_name='h_comment_history')
    op.drop_index(op.f('ix_h_comment_history_event_author'), table_name='h_comment_history')
    op.drop_index(op.f('ix_h_comment_history_deleted_at'), table_name='h_comment_history')
    op.drop_index(op.f('ix_h_comment_history_created_at'), table_name='h_comment_history')
    op.drop_index(op.f('ix_h_comment_history_comment_uuid'), table_name='h_comment_history')
    op.drop_index(op.f('ix_h_comment_history_comment_author'), table_name='h_comment_history')
    op.drop_table('h_comment_history')
    # ### end Alembic commands ###
