"""Add verification status to history column

Revision ID: ac6cbacd3363
Revises: d7db3857f866
Create Date: 2021-05-22 15:01:31.802128

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac6cbacd3363'
down_revision = '40855c20ecf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('h_verification_history', sa.Column('verification_status', sa.String(), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('h_verification_history', 'verification_status')
