"""add translation tables

Revision ID: 4919005446db
Revises: 522937d7ded9
Create Date: 2021-06-25 12:17:22.526965

"""
from alembic import op
import sqlalchemy as sa
from figure1.common.types import Locale
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4919005446db'
down_revision = '522937d7ded9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('c_content_translation',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('case_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('source_language', sa.Text(), nullable=True),
    sa.Column('target_language', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=10000), nullable=True),
    sa.Column('caption', sa.String(length=100000), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['c_case.case_uuid'], name=op.f('fk_c_content_translation_case_uuid_c_case')),
    sa.ForeignKeyConstraint(['content_uuid'], ['c_content.content_uuid'], name=op.f('fk_c_content_translation_content_uuid_c_content')),
    sa.PrimaryKeyConstraint('content_uuid', 'target_language', name=op.f('pk_c_content_translation'))
    )
    op.create_index(op.f('ix_c_content_translation_created_at'), 'c_content_translation', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_content_translation_updated_at'), 'c_content_translation', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():

    op.drop_index(op.f('ix_c_content_translation_updated_at'), table_name='c_content_translation')
    op.drop_index(op.f('ix_c_content_translation_created_at'), table_name='c_content_translation')
    op.drop_table('c_content_translation')

    # ### end Alembic commands ###
