"""agg columns for content and cases

Revision ID: 8fff4bed7eb5
Revises: 5cbfb1fb9590
Create Date: 2021-05-17 15:31:26.893124

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fff4bed7eb5'
down_revision = '5cbfb1fb9590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('c_content', sa.Column('approved_comments_count', sa.Integer(), nullable=True))
    op.add_column('c_content', sa.Column('reported_comments_count', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_content', 'reported_comments_count')
    op.drop_column('c_content', 'approved_comments_count')
    # ### end Alembic commands ###
