"""Communication channel updates

Revision ID: 01b1fffb3cab
Revises: e8a2d3ffbdd4
Create Date: 2021-10-14 16:02:52.060316

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01b1fffb3cab'
down_revision = 'e8a2d3ffbdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_communication_channel',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('communication_channel_uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('communication_channel_name', sa.Text(), nullable=True),
        sa.Column('communication_channel_id', sa.Integer(), nullable=True),
        sa.Column('communication_default_setting', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('communication_channel_uuid', name=op.f('pk_r_communication_channel'))
    )
    op.create_index(op.f('ix_r_communication_channel_created_at'), 'r_communication_channel', ['created_at'], unique=False)
    op.create_index(op.f('ix_r_communication_channel_deleted_at'), 'r_communication_channel', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_r_communication_channel_updated_at'), 'r_communication_channel', ['updated_at'], unique=False)

    op.create_table('u_user_communication_channel_preferences',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('communication_channel_uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('communication_setting', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['communication_channel_uuid'], ['r_communication_channel.communication_channel_uuid'], name=op.f('fk_u_user_communication_channel_preferences_communication_channel_uuid_r_communication_channel')),
        sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'], name=op.f('fk_u_user_communication_channel_preferences_user_uuid_u_user')),
        sa.PrimaryKeyConstraint('user_uuid', 'communication_channel_uuid', name=op.f('pk_u_user_communication_channel_preferences'))
    )
    op.create_index(op.f('ix_u_user_communication_channel_preferences_created_at'), 'u_user_communication_channel_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_u_user_communication_channel_preferences_deleted_at'), 'u_user_communication_channel_preferences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_u_user_communication_channel_preferences_updated_at'), 'u_user_communication_channel_preferences', ['updated_at'], unique=False)

    op.add_column('r_communication_settings', sa.Column('communication_channel_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_r_communication_settings_communication_channel_uuid_r_communication_channel'), 'r_communication_settings', 'r_communication_channel', ['communication_channel_uuid'], ['communication_channel_uuid'])


def downgrade():
    op.drop_constraint(op.f('fk_r_communication_settings_communication_channel_uuid_r_communication_channel'), 'r_communication_settings', type_='foreignkey')
    op.drop_column('r_communication_settings', 'communication_channel_uuid')

    op.drop_index(op.f('ix_u_user_communication_channel_preferences_updated_at'), table_name='u_user_communication_channel_preferences')
    op.drop_index(op.f('ix_u_user_communication_channel_preferences_deleted_at'), table_name='u_user_communication_channel_preferences')
    op.drop_index(op.f('ix_u_user_communication_channel_preferences_created_at'), table_name='u_user_communication_channel_preferences')
    op.drop_table('u_user_communication_channel_preferences')

    op.drop_index(op.f('ix_r_communication_channel_updated_at'), table_name='r_communication_channel')
    op.drop_index(op.f('ix_r_communication_channel_deleted_at'), table_name='r_communication_channel')
    op.drop_index(op.f('ix_r_communication_channel_created_at'), table_name='r_communication_channel')
    op.drop_table('r_communication_channel')
    # ### end Alembic commands ###
