"""update communication groups settings with a new text
in the name field
Revision ID: d5e57c3d4f23
Revises: e38da52b6071
Create Date: 2021-11-04 13:31:12.715447

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5e57c3d4f23'
down_revision = 'e38da52b6071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE r_communication_groups SET communication_group_name='Newly shared cases in your specialty requiring time sensitive insights' WHERE communication_group_name='Paging my specialty'")


def downgrade():
    pass
