"""Add last sync date for activity sync and iterable sync

Revision ID: 1d1ce55743d7
Revises: d5e57c3d4f23
Create Date: 2021-11-10 13:10:29.121956

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d1ce55743d7'
down_revision = 'd5e57c3d4f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_user_state', sa.Column('last_activity_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('u_user_state', sa.Column('last_iterable_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('u_user_state', 'last_iterable_sync')
    op.drop_column('u_user_state', 'last_activity_sync')

    # ### end Alembic commands ###
