"""approved case count

Revision ID: 10c2b19bb908
Revises: 71af355f2eda
Create Date: 2021-05-19 10:09:49.183501

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c2b19bb908'
down_revision = '71af355f2eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('u_user', sa.Column('approved_case_count', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('u_user', 'approved_case_count')
    # ### end Alembic commands ###
