"""copy user state

Revision ID: 692e7ea98f4e
Revises: 9327b9ff4847
Create Date: 2021-06-23 15:28:28.743500

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '692e7ea98f4e'
down_revision = '9327b9ff4847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    update u_user_state set (last_seen, onboarding_completed, onboarding_interests_completed, hidden_from_search, user_uid) = (
    select coalesce(last_seen, updated_at, created_at),
           u_user.onboarding_completed,
           u_user.onboarding_interests_completed,
           u_user.hidden_from_search,
           u_user.user_uid
    from u_user where  u_user.user_uuid=u_user_state.user_uuid)
    """)
    # ### end Alembic commands ###


def downgrade():
    pass

