"""add feed preview table

Revision ID: e773a6cb68b5
Revises: 630b63b572fd
Create Date: 2021-09-13 15:02:03.183312

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e773a6cb68b5'
down_revision = '630b63b572fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f_feed_previews',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feed_type_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('last_run_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feed_type_uuid'], ['f_feed_type.feed_type_uuid'], name=op.f('fk_f_feed_previews_feed_type_uuid_f_feed_type')),
    sa.PrimaryKeyConstraint('feed_type_uuid', name=op.f('pk_f_feed_previews'))
    )
    op.create_index(op.f('ix_f_feed_previews_created_at'), 'f_feed_previews', ['created_at'], unique=False)
    op.create_index(op.f('ix_f_feed_previews_deleted_at'), 'f_feed_previews', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_f_feed_previews_updated_at'), 'f_feed_previews', ['updated_at'], unique=False)

    op.sync_enum_values('public', 'feedkind', ['EVERYTHING', 'MADE_FOR_YOU', 'SEARCH', 'TOPIC'], ['EVERYTHING', 'MADE_FOR_YOU', 'PREVIEW', 'SEARCH', 'TOPIC'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'feedkind', ['EVERYTHING', 'MADE_FOR_YOU', 'PREVIEW', 'SEARCH', 'TOPIC'], ['EVERYTHING', 'MADE_FOR_YOU', 'SEARCH', 'TOPIC'])
    op.drop_constraint(op.f('fk_c_campaign_case_moderator_uuid_u_user'), 'c_campaign_case', type_='foreignkey')
    op.drop_index(op.f('ix_f_feed_previews_updated_at'), table_name='f_feed_previews')
    op.drop_index(op.f('ix_f_feed_previews_deleted_at'), table_name='f_feed_previews')
    op.drop_index(op.f('ix_f_feed_previews_created_at'), table_name='f_feed_previews')
    op.drop_table('f_feed_previews')
    # ### end Alembic commands ###
