""" update figure1 internal users

Revision ID: dda0971c7fe5
Revises: 483f1b8d9fd5
Create Date: 2021-10-08 13:11:41.177574

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dda0971c7fe5'
down_revision = '483f1b8d9fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE u_user SET hidden_from_search=true WHERE user_type='FIGURE1_INTERNAL'")
    op.execute("UPDATE u_user_state SET hidden_from_search=u_user.hidden_from_search FROM u_user WHERE u_user.user_uuid=u_user_state.user_uuid AND u_user.deleted_at IS NULL AND u_user.user_type='FIGURE1_INTERNAL'")


def downgrade():
    pass
