"""add public taxonomy tables

Revision ID: 6e68ec993fdb
Revises: 4c16469e4fdf
Create Date: 2021-11-12 11:58:58.821544

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e68ec993fdb'
down_revision = '4c16469e4fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_public_specialty_taxonomy',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('code', sa.Text(), nullable=False),
                    sa.Column('grouping', sa.Text(), nullable=True),
                    sa.Column('classification', sa.Text(), nullable=True),
                    sa.Column('specialization', sa.Text(), nullable=True),
                    sa.Column('definition', sa.Text(), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('display_name', sa.Text(), nullable=True),
                    sa.Column('section', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('code', name=op.f('pk_r_public_specialty_taxonomy'))
                    )
    op.create_index(op.f('ix_r_public_specialty_taxonomy_created_at'), 'r_public_specialty_taxonomy', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_r_public_specialty_taxonomy_updated_at'), 'r_public_specialty_taxonomy', ['updated_at'],
                    unique=False)
    op.create_table('r_specialty_taxonomy_map',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('taxonomy_code', sa.Text(), nullable=False),
                    sa.Column('specialty_tree_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['taxonomy_code'], ['r_public_specialty_taxonomy.code'], name=op.f(
                        'fk_r_specialty_taxonomy_map_taxonomy_code_r_public_specialty_taxonomy')),
                    sa.PrimaryKeyConstraint('taxonomy_code', name=op.f('pk_r_specialty_taxonomy_map'))
                    )
    op.create_index(op.f('ix_r_specialty_taxonomy_map_created_at'), 'r_specialty_taxonomy_map', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_r_specialty_taxonomy_map_updated_at'), 'r_specialty_taxonomy_map', ['updated_at'],
                    unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_r_specialty_taxonomy_map_updated_at'), table_name='r_specialty_taxonomy_map')
    op.drop_index(op.f('ix_r_specialty_taxonomy_map_created_at'), table_name='r_specialty_taxonomy_map')
    op.drop_table('r_specialty_taxonomy_map')
    op.drop_index(op.f('ix_r_public_specialty_taxonomy_updated_at'), table_name='r_public_specialty_taxonomy')
    op.drop_index(op.f('ix_r_public_specialty_taxonomy_created_at'), table_name='r_public_specialty_taxonomy')
    op.drop_table('r_public_specialty_taxonomy')
    # ### end Alembic commands ###
