"""cleanup api

Revision ID: 3b79cdaefa72
Revises: 9c3965bcccdd
Create Date: 2021-05-26 17:01:38.550579

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b79cdaefa72'
down_revision = '9c3965bcccdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_user_role_created_at', table_name='api_user_role')
    op.drop_index('ix_api_user_role_deleted_at', table_name='api_user_role')
    op.drop_index('ix_api_user_role_updated_at', table_name='api_user_role')
    op.drop_constraint('uq_api_user_api_user_name', 'api_user', type_='unique')
    op.drop_constraint('fk_api_user_api_user_role_api_user_role', 'api_user', type_='foreignkey')
    op.drop_table('api_user_role')

    op.drop_column('api_user', 'api_user_role')
    op.drop_column('api_user', 'api_user_name')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('api_user_role',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('api_role_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_role_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_role_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_role_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('api_role_uuid', name='pk_api_user_role'),
    sa.UniqueConstraint('api_role_name', name='uq_api_user_role_api_role_name')
    )
    op.add_column('api_user', sa.Column('api_user_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_user', sa.Column('api_user_role', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_api_user_api_user_role_api_user_role', 'api_user', 'api_user_role', ['api_user_role'], ['api_role_uuid'])
    op.create_unique_constraint('uq_api_user_api_user_name', 'api_user', ['api_user_name'])
    op.create_index('ix_api_user_role_updated_at', 'api_user_role', ['updated_at'], unique=False)
    op.create_index('ix_api_user_role_deleted_at', 'api_user_role', ['deleted_at'], unique=False)
    op.create_index('ix_api_user_role_created_at', 'api_user_role', ['created_at'], unique=False)
    # ### end Alembic commands ###
