"""add columns to user state

Revision ID: af29ffc38051
Revises: ab476aa5bda6
Create Date: 2021-05-07 10:26:32.870567

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af29ffc38051'
down_revision = 'ab476aa5bda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('u_user_state', sa.Column('case_reported_count', sa.Integer(), nullable=True))
    op.add_column('u_user_state', sa.Column('case_uploaded_count', sa.Integer(), nullable=True))
    op.add_column('u_user_state', sa.Column('comment_authored_count', sa.Integer(), nullable=True))
    op.add_column('u_user_state', sa.Column('comment_deleted_count', sa.Integer(), nullable=True))
    op.add_column('u_user_state', sa.Column('comment_reported_count', sa.Integer(), nullable=True))
    op.add_column('u_user_state', sa.Column('comment_reports_count', sa.Integer(), nullable=True))
    op.add_column('u_user_state', sa.Column('last_comment', sa.DateTime(timezone=True), nullable=True))
    op.add_column('u_user_state', sa.Column('last_case_upload', sa.DateTime(timezone=True), nullable=True))
    op.add_column('u_user_state', sa.Column('user_uid', sa.Text(), nullable=True))
    op.create_index(op.f('ix_u_user_state_user_uid'), 'u_user_state', ['user_uid'], unique=True)
    op.drop_column('u_user_state', 'last_synced_activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_user_state', sa.Column('last_synced_activity', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_u_user_state_user_uid'), table_name='u_user_state')
    op.drop_column('u_user_state', 'user_uid')
    op.drop_column('u_user_state', 'comment_reports_count')
    op.drop_column('u_user_state', 'comment_reported_count')
    op.drop_column('u_user_state', 'comment_deleted_count')
    op.drop_column('u_user_state', 'comment_authored_count')
    op.drop_column('u_user_state', 'case_uploaded_count')
    op.drop_column('u_user_state', 'case_reported_count')
    op.drop_column('u_user_state', 'last_comment')
    op.drop_column('u_user_state', 'last_case_upload')
