"""clean up device token table

Revision ID: 58f5611affd4
Revises: 6c74440afacc
Create Date: 2021-06-16 19:06:10.144987

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58f5611affd4'
down_revision = '6c74440afacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('n_user_device_notification_token', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('_user_device_uc', 'n_user_device_notification_token', type_='unique')
    op.drop_column('n_user_device_notification_token', 'user_device_notification_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('n_user_device_notification_token', sa.Column('user_device_notification_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('_user_device_uc', 'n_user_device_notification_token', ['user_uuid', 'device_id'])
    op.alter_column('n_user_device_notification_token', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)

    # ### end Alembic commands ###
