"""topic language setting

Revision ID: 6af5ab29137a
Revises: 9327b9ff4847
Create Date: 2021-06-23 16:06:06.113119

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6af5ab29137a'
down_revision = '9327b9ff4847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('f_topic', sa.Column('topic_language', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('f_topic', 'topic_language')
    # ### end Alembic commands ###
