"""remove a foreign key constraint from case progress table

Revision ID: a4747e02b539
Revises: 05e77d2bc322
Create Date: 2021-12-07 15:09:38.711402

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4747e02b539'
down_revision = '05e77d2bc322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_c_case_progress_user_uuid_u_user', 'c_case_progress', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_c_case_progress_user_uuid_u_user', 'c_case_progress', 'u_user', ['user_uuid'], ['user_uuid'])
    # ### end Alembic commands ###
