"""Add category enum to settings

Revision ID: 42f19071c92a
Revises: aa835b78b8ad
Create Date: 2021-09-07 15:43:53.117844

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42f19071c92a'
down_revision = 'aa835b78b8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM.create(postgresql.ENUM('CommentsRepliesLikes', 'Paging', 'Follow', 'SavedCases', 'WeeklyDigest', name='activitynotificationcategories'), bind=op.get_bind())
    op.add_column('r_communication_groups', sa.Column('communication_group_category', postgresql.ENUM(name='activitynotificationcategories'), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('r_communication_groups', 'communication_group_category')
    postgresql.ENUM.drop(postgresql.ENUM(name='activitynotificationcategories'), bind=op.get_bind())
    # ### end Alembic commands ###
