""" modifying a constraint in the user
npi table
Revision ID: a0a595f39ba5
Revises: 6b1ec2d47c02
Create Date: 2021-12-21 22:57:30.841149

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0a595f39ba5'
down_revision = '6b1ec2d47c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('u_user_npi', 'npi_postal_code',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('u_user_npi', 'npi_postal_code',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
