"""add is_anonymous to Case

Revision ID: dbc403fdb5d6
Revises: 72d901c88b45
Create Date: 2022-06-09 15:26:02.382363

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbc403fdb5d6'
down_revision = '72d901c88b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_case', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_case', 'is_anonymous')
    # ### end Alembic commands ###
