"""remove_user_uuid_not_null_constraint

Revision ID: 41c4028a0d6c
Revises: 22e6d415d07d
Create Date: 2022-02-07 10:00:43.486382

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41c4028a0d6c'
down_revision = '22e6d415d07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g_group_member_filter', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g_group_member_filter', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
