"""add unique mesh terms case uuid index

Revision ID: b909364bc2ac
Revises: b1cc6c12ffad
Create Date: 2022-03-01 15:18:00.731621

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b909364bc2ac'
down_revision = 'b1cc6c12ffad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_c_mesh_terms_case_uuid'), 'c_mesh_terms', ['case_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_c_mesh_terms_case_uuid'), table_name='c_mesh_terms')
    # ### end Alembic commands ###
