"""add_request_help_column_to_case_model

Revision ID: 3690c966b448
Revises: 6d61fd0fabd8
Create Date: 2022-02-28 15:38:05.637923

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3690c966b448'
down_revision = '6d61fd0fabd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_case', sa.Column('request_help', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_case', 'request_help')
    # ### end Alembic commands ###
