"""Add standalone email type - LOGIN_LINK

Revision ID: 32518d77cdca
Revises: 70d03465c5e3
Create Date: 2022-10-18 10:33:25.263544

"""
from alembic import op
import sqlalchemy as sa
from figure1.common.utils import update_enum

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32518d77cdca'
down_revision = '70d03465c5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('standaloneemailkind',
                ['CONTACT_SUPPORT',
                 'LOGIN_LINK',
                 'RESET_PASSWORD'],
                'n_standalone_email',
                'kind',
                {}
                )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('standaloneemailkind',
                ['CONTACT_SUPPORT',
                 'RESET_PASSWORD'],
                'n_standalone_email',
                'kind',
                {}
                )
    # ### end Alembic commands ###
