"""add source to UserVerification

Revision ID: 19089542103a
Revises: c1d75a1d03a3
Create Date: 2022-11-29 08:12:27.531026

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from figure1.common.utils import create_enum
from figure1.common.utils import delete_enum

# revision identifiers, used by Alembic.
revision = '19089542103a'
down_revision = 'c1d75a1d03a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum(enum_name='userverificationsource', values=['DMD'])
    op.add_column('u_user_verification',
                  sa.Column('source',
                            sa.Enum('DMD', name='userverificationsource'),
                            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('u_user_verification', 'source')
    delete_enum('userverificationsource')
    # ### end Alembic commands ###
