"""add question table

Revision ID: a07dac5e250a
Revises: b34d970a28aa
Create Date: 2022-05-31 15:28:28.320434

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a07dac5e250a'
down_revision = 'b34d970a28aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_question',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('question_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('question_set_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('question_set_label', sa.Text(), nullable=True),
                    sa.Column('question_text', sa.Text(), nullable=True),
                    sa.Column('next_question', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('display_order', sa.Integer(), nullable=True),
                    sa.Column('is_free_form', sa.Boolean(), nullable=True),
                    sa.Column('is_first_question', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('question_uuid', name=op.f('pk_c_question'))
                    )
    op.create_index(op.f('ix_c_question_created_at'), 'c_question', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_question_deleted_at'), 'c_question', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_c_question_updated_at'), 'c_question', ['updated_at'], unique=False)
    op.create_table('c_question_answer_option',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('question_uuid', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('answer_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('answer_text', sa.Text(), nullable=True),
                    sa.Column('next_question', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.ForeignKeyConstraint(['next_question'], ['c_question.question_uuid'],
                                            name=op.f('fk_c_question_answer_option_next_question_c_question')),
                    sa.ForeignKeyConstraint(['question_uuid'], ['c_question.question_uuid'],
                                            name=op.f('fk_c_question_answer_option_question_uuid_c_question')),
                    sa.PrimaryKeyConstraint('answer_uuid', name=op.f('pk_c_question_answer_option'))
                    )
    op.create_index(op.f('ix_c_question_answer_option_created_at'), 'c_question_answer_option', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_c_question_answer_option_deleted_at'), 'c_question_answer_option', ['deleted_at'],
                    unique=False)
    op.create_index(op.f('ix_c_question_answer_option_updated_at'), 'c_question_answer_option', ['updated_at'],
                    unique=False)
    op.create_table('c_case_cme_user_answer',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('case_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('question_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('user_answer_uuid', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('user_answer_text', sa.Text(), nullable=True),
                    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['case_uuid'], ['c_case.case_uuid'],
                                            name=op.f('fk_c_case_cme_user_answer_case_uuid_c_case')),
                    sa.ForeignKeyConstraint(['question_uuid'], ['c_question.question_uuid'],
                                            name=op.f('fk_c_case_cme_user_answer_question_uuid_c_question')),
                    sa.ForeignKeyConstraint(['user_answer_uuid'], ['c_question_answer_option.answer_uuid'], name=op.f(
                        'fk_c_case_cme_user_answer_user_answer_uuid_c_question_answer_option')),
                    sa.ForeignKeyConstraint(['user_uuid'], ['u_user.user_uuid'],
                                            name=op.f('fk_c_case_cme_user_answer_user_uuid_u_user')),
                    sa.PrimaryKeyConstraint('case_uuid', 'question_uuid', name=op.f('pk_c_case_cme_user_answer'))
                    )
    op.create_index(op.f('ix_c_case_cme_user_answer_created_at'), 'c_case_cme_user_answer', ['created_at'],
                    unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_c_case_cme_user_answer_created_at'), table_name='c_case_cme_user_answer')
    op.drop_table('c_case_cme_user_answer')
    op.drop_index(op.f('ix_c_question_answer_option_updated_at'), table_name='c_question_answer_option')
    op.drop_index(op.f('ix_c_question_answer_option_deleted_at'), table_name='c_question_answer_option')
    op.drop_index(op.f('ix_c_question_answer_option_created_at'), table_name='c_question_answer_option')
    op.drop_table('c_question_answer_option')
    op.drop_index(op.f('ix_c_question_updated_at'), table_name='c_question')
    op.drop_index(op.f('ix_c_question_deleted_at'), table_name='c_question')
    op.drop_index(op.f('ix_c_question_created_at'), table_name='c_question')
    op.drop_table('c_question')
    # ### end Alembic commands ###
