"""Add ProfessionChanged notification

Revision ID: 24e9463960fe
Revises: 22982d22a2ce
Create Date: 2022-04-22 16:32:10.414998

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
from figure1.common.utils import update_enum

# revision identifiers, used by Alembic.
revision = '24e9463960fe'
down_revision = '22982d22a2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'COMMENT',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'MODERATION_ACTIVITY',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_UPDATE',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'SAVED_CASE_DIAGNOSIS',
                 'LIKED_CASE_DIAGNOSIS',
                 'CASE_NOT_DIAGNOSIS_CHOSEN',
                 'PROFESSION_CHANGE_APPROVED'
                 ],
                'n_user_notification',
                'notification_type',
                {})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'COMMENT',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'MODERATION_ACTIVITY',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_UPDATE',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'SAVED_CASE_DIAGNOSIS',
                 'LIKED_CASE_DIAGNOSIS',
                 'CASE_NOT_DIAGNOSIS_CHOSEN'
                 ],
                'n_user_notification',
                'notification_type',
                {'PROFESSION_CHANGE_APPROVED': 'NULL'})
    # ### end Alembic commands ###
