"""Add comment translations

Revision ID: 22e6d415d07d
Revises: d43d8b90821b
Create Date: 2022-02-04 09:57:22.637657

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22e6d415d07d'
down_revision = 'd43d8b90821b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_comment_translations',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('translation_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('comment_uuid', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('language', sa.Text(), nullable=True),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['comment_uuid'], ['c_comment.comment_uuid'],
                                            name=op.f('fk_t_comment_translations_comment_uuid_c_comment')),
                    sa.PrimaryKeyConstraint('translation_uuid', name=op.f('pk_t_comment_translations'))
                    )
    op.create_index(op.f('ix_t_comment_translations_comment_uuid'), 't_comment_translations', ['comment_uuid'],
                    unique=False)
    op.create_index(op.f('ix_t_comment_translations_created_at'), 't_comment_translations', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_t_comment_translations_deleted_at'), 't_comment_translations', ['deleted_at'],
                    unique=False)
    op.create_index(op.f('ix_t_comment_translations_updated_at'), 't_comment_translations', ['updated_at'],
                    unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_comment_translations_updated_at'), table_name='t_comment_translations')
    op.drop_index(op.f('ix_t_comment_translations_deleted_at'), table_name='t_comment_translations')
    op.drop_index(op.f('ix_t_comment_translations_created_at'), table_name='t_comment_translations')
    op.drop_index(op.f('ix_t_comment_translations_comment_uuid'), table_name='t_comment_translations')
    op.drop_table('t_comment_translations')
    # ### end Alembic commands ###
