"""add_content_update_translation new

Revision ID: 65788eb83a52
Revises: 2ead677435d0
Create Date: 2022-02-17 00:08:01.122668

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65788eb83a52'
down_revision = '2ead677435d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_content_update_translations',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('update_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('language', sa.Text(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['update_uuid'], ['c_content_update.update_uuid'], name=op.f('fk_c_content_update_translations_update_uuid_c_content_update')),
                    sa.PrimaryKeyConstraint('update_uuid', 'language', name=op.f('pk_c_content_update_translations'))
    )
    op.create_index(op.f('ix_c_content_update_translations_created_at'), 'c_content_update_translations', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_content_update_translations_deleted_at'), 'c_content_update_translations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_c_content_update_translations_update_uuid'), 'c_content_update_translations', ['update_uuid'], unique=False)
    op.create_index(op.f('ix_c_content_update_translations_updated_at'), 'c_content_update_translations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_c_content_update_translations_updated_at'), table_name='c_content_update_translations')
    op.drop_index(op.f('ix_c_content_update_translations_update_uuid'), table_name='c_content_update_translations')
    op.drop_index(op.f('ix_c_content_update_translations_deleted_at'), table_name='c_content_update_translations')
    op.drop_index(op.f('ix_c_content_update_translations_created_at'), table_name='c_content_update_translations')
    op.drop_table('c_content_update_translations')
    # ### end Alembic commands ###
