"""Add answer group

Revision ID: 72d901c88b45
Revises: 10f60ff0db2b
Create Date: 2022-06-09 13:11:54.400726

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72d901c88b45'
down_revision = '10f60ff0db2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_answer_group',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('answer_group_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('question_uuid', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('answer_group_heading', sa.Text(), nullable=True),
                    sa.Column('answer_group_display_order', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['question_uuid'], ['c_question.question_uuid'],
                                            name=op.f('fk_c_answer_group_question_uuid_c_question')),
                    sa.PrimaryKeyConstraint('answer_group_uuid', name=op.f('pk_c_answer_group'))
                    )
    op.create_index(op.f('ix_c_answer_group_created_at'), 'c_answer_group', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_answer_group_deleted_at'), 'c_answer_group', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_c_answer_group_updated_at'), 'c_answer_group', ['updated_at'], unique=False)

    op.add_column('c_question', sa.Column('question_type', sa.Text(), nullable=True))
    op.drop_column('c_question', 'is_free_form')
    op.drop_column('c_question', 'is_first_question')
    op.add_column('c_question_answer_option', sa.Column('answer_suggested_text', sa.Text(), nullable=True))
    op.add_column('c_question_answer_option', sa.Column('has_extra_input', sa.Boolean(), nullable=True))
    op.add_column('c_question_answer_option',
                  sa.Column('answer_group_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('c_question_answer_option', sa.Column('answer_display_order', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_c_question_answer_option_answer_group_uuid_c_answer_group'),
                          'c_question_answer_option', 'c_answer_group', ['answer_group_uuid'], ['answer_group_uuid'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('fk_c_question_answer_option_answer_group_uuid_c_answer_group'), 'c_question_answer_option',
                       type_='foreignkey')
    op.drop_column('c_question_answer_option', 'answer_display_order')
    op.drop_column('c_question_answer_option', 'answer_group_uuid')
    op.drop_column('c_question_answer_option', 'has_extra_input')
    op.drop_column('c_question_answer_option', 'answer_suggested_text')
    op.add_column('c_question', sa.Column('is_first_question', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('c_question', sa.Column('is_free_form', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('c_question', 'question_type')
    op.drop_index(op.f('ix_c_answer_group_updated_at'), table_name='c_answer_group')
    op.drop_index(op.f('ix_c_answer_group_deleted_at'), table_name='c_answer_group')
    op.drop_index(op.f('ix_c_answer_group_created_at'), table_name='c_answer_group')
    op.drop_table('c_answer_group')
    # ### end Alembic commands ###
