"""update usernotificationtype

Revision ID: 4dc9c429d27e
Revises: 5a3c63d4d32e
Create Date: 2022-04-19 07:47:03.017962

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from figure1.common.utils import update_enum

revision = '4dc9c429d27e'
down_revision = '5a3c63d4d32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'COMMENT',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'MODERATION_ACTIVITY',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_UPDATE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN'],
                'n_user_notification',
                'notification_type',
                {})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'COMMENT',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'MODERATION_ACTIVITY',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_UPDATE'],
                'n_user_notification',
                'notification_type',
                {'CASE_NOT_DIAGNOSIS_CHOSEN': 'NULL'})
    # ### end Alembic commands ###
