"""update usernotificationtype for new Diagnosis

Revision ID: 655635605cd0
Revises: 4dc9c429d27e
Create Date: 2022-04-19 13:16:27.490404

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from figure1.common.utils import update_enum

revision = '655635605cd0'
down_revision = '4dc9c429d27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE', 'CASE_DELETE',
                 'COMMENT', 'COMMENT_DELETE',
                 'COMMENT_REPLY', 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE', 'COMMENT_SAVED_CASE_OP',
                 'MODERATION_ACTIVITY', 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP', 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER', 'PAGING',
                 'REACT', 'REJECT',
                 'SAVED_CASE_UPDATE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'SAVED_CASE_DIAGNOSIS',
                 'LIKED_CASE_DIAGNOSIS'],
                'n_user_notification',
                'notification_type',
                {})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE', 'CASE_DELETE',
                 'COMMENT', 'COMMENT_DELETE',
                 'COMMENT_REPLY', 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE', 'COMMENT_SAVED_CASE_OP',
                 'MODERATION_ACTIVITY', 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP', 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER', 'PAGING',
                 'REACT', 'REJECT',
                 'SAVED_CASE_UPDATE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN'],
                'n_user_notification',
                'notification_type',
                {'COMMENTED_CASE_DIAGNOSIS': 'NULL',
                 'SAVED_CASE_DIAGNOSIS': 'NULL',
                 'LIKED_CASE_DIAGNOSIS': 'NULL'})
    # ### end Alembic commands ###

