"""add is_anonymous to Comment

Revision ID: b33f16bd23b6
Revises: dbc403fdb5d6
Create Date: 2022-06-27 18:13:40.942821

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b33f16bd23b6'
down_revision = 'dbc403fdb5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_comment', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_comment', 'is_anonymous')
    # ### end Alembic commands ###
