"""Add has_comments column to c_content

Revision ID: 993f6ed0281e
Revises: cea7a78c19a6
Create Date: 2022-11-03 13:58:23.269573

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '993f6ed0281e'
down_revision = 'cea7a78c19a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_content', sa.Column('has_comments', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_content', 'has_comments')

    # ### end Alembic commands ###
