"""modify mesh terms table
There are some mesh entries with empty case_uuids, these are deleted here. There are also 3 cases that do not
link to the c_cases table, these are deleted here as well.

Revision ID: 77784609c4dd
Revises: a2c213926776
Create Date: 2022-02-23 11:19:02.459804

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77784609c4dd'
down_revision = 'a2c213926776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_c_mesh_terms_case_uuid', table_name='c_mesh_terms')
    op.execute("""DELETE FROM c_mesh_terms where case_uuid is null""")

    op.execute("""with delete_unlinked as (
    select cmt.case_uuid as ccuid
    from c_mesh_terms cmt left join c_case cc on cmt.case_uuid = cc.case_uuid
    where cmt.case_uuid is not null and cc.case_uuid is null
    )
DELETE from c_mesh_terms where case_uuid in (select ccuid from delete_unlinked)""")
    op.alter_column('c_mesh_terms', 'case_uuid',
                    type_=postgresql.UUID(),
                    nullable=False)
    op.create_foreign_key(op.f('fk_c_mesh_terms_case_uuid_c_case'), 'c_mesh_terms', 'c_case', ['case_uuid'],
                          ['case_uuid'])

    op.drop_column('c_mesh_terms', 'comment_terms')
    op.drop_column('c_mesh_terms', 'mesh_attempts')
    op.drop_column('c_mesh_terms', 'caption_terms_complete')
    op.drop_column('c_mesh_terms', 'comment_terms_complete')
    op.drop_column('c_mesh_terms', 'caption_terms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('c_mesh_terms',
                  sa.Column('caption_terms', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('c_mesh_terms', sa.Column('comment_terms_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('c_mesh_terms', sa.Column('caption_terms_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('c_mesh_terms', sa.Column('mesh_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('c_mesh_terms',
                  sa.Column('comment_terms', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_c_mesh_terms_case_uuid_c_case'), 'c_mesh_terms', type_='foreignkey')
    op.create_index('ix_c_mesh_terms_case_uuid', 'c_mesh_terms', ['case_uuid'], unique=False)
    op.alter_column('c_mesh_terms', 'case_uuid',
                    existing_type=postgresql.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
