"""add linked_update_uuid

Revision ID: 604f14a38544
Revises: 24e9463960fe
Create Date: 2022-04-27 11:21:08.947929

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '604f14a38544'
down_revision = '24e9463960fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_content_update', sa.Column('linked_update_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_content_update', 'linked_update_uuid')
    # ### end Alembic commands ###
