"""add group_creator_uuid to groups

Revision ID: 21ff0ee696cf
Revises: ade5189cabbf
Create Date: 2022-05-10 12:40:38.032337

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21ff0ee696cf'
down_revision = 'ade5189cabbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g_groups', sa.Column('group_creator_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_g_groups_group_creator_uuid_u_user'),
                          'g_groups',
                          'u_user',
                          ['group_creator_uuid'],
                          ['user_uuid'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_g_groups_group_creator_uuid_u_user'), 'g_groups', type_='foreignkey')
    op.drop_column('g_groups', 'group_creator_uuid')
    # ### end Alembic commands ###
