"""Make ContentUpdate.text not nullable

Revision ID: 5a3c63d4d32e
Revises: 77c8a891c998
Create Date: 2022-04-18 08:19:59.555057

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a3c63d4d32e'
down_revision = '77c8a891c998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE from c_content_update where text is null")
    op.alter_column('c_content_update', 'text',
                    existing_type=sa.VARCHAR(length=100000),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('c_content_update', 'text',
                    existing_type=sa.VARCHAR(length=100000),
                    nullable=True)
    # ### end Alembic commands ###
