"""Add user verification table changes

Revision ID: 77c8a891c998
Revises: a8772deadecd
Create Date: 2022-04-01 12:22:05.404704

"""
from figure1.common.utils import update_enum
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = '77c8a891c998'
down_revision = 'a8772deadecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_u_user_verification_change_request_verification_uuid_u_user_verification'),
    #                    'u_user_verification_change_request', type_='foreignkey')
    # op.drop_table('u_user_verification_change_request')
    op.create_table('u_user_verification_change_request',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('verification_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('requested_profession', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['verification_uuid'], ['u_user_verification.verification_uuid'], name=op.f(
                        'fk_u_user_verification_change_request_verification_uuid_u_user_verification'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('verification_uuid', name=op.f('pk_u_user_verification_change_request'))
                    )
    op.create_index(op.f('ix_u_user_verification_change_request_created_at'), 'u_user_verification_change_request',
                    ['created_at'], unique=False)
    op.create_index(op.f('ix_u_user_verification_change_request_updated_at'), 'u_user_verification_change_request',
                    ['updated_at'], unique=False)

    op.add_column('u_user_license', sa.Column('verification_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute(
        """UPDATE u_user_license ul 
        SET verification_uuid=uv.verification_uuid 
        from u_user_verification uv where uv.user_uuid=ul.user_uuid""")
    op.execute("""DELETE from u_user_license where verification_uuid is null""")
    op.alter_column('u_user_license', 'verification_uuid', nullable=False)
    op.drop_index('ix_u_user_license_user_uuid', table_name='u_user_license')
    op.create_index(op.f('ix_u_user_license_user_uuid'), 'u_user_license', ['user_uuid'], unique=False)
    op.create_foreign_key(op.f('fk_u_user_license_verification_uuid_u_user_verification'), 'u_user_license',
                          'u_user_verification', ['verification_uuid'], ['verification_uuid'], ondelete='CASCADE')
    op.drop_column('u_user_license', 'license_uuid')
    op.add_column('u_user_npi', sa.Column('verification_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute(
        """UPDATE u_user_npi ul 
        SET verification_uuid=uv.verification_uuid 
        from u_user_verification uv where uv.user_uuid=ul.user_uuid""")
    op.execute("""DELETE from u_user_npi where verification_uuid is null""")
    op.alter_column('u_user_npi', 'verification_uuid', nullable=False)
    op.drop_index('ix_u_user_npi_user_uuid', table_name='u_user_npi')
    op.create_index(op.f('ix_u_user_npi_user_uuid'), 'u_user_npi', ['user_uuid'], unique=False)
    op.create_foreign_key(op.f('fk_u_user_npi_verification_uuid_u_user_verification'), 'u_user_npi',
                          'u_user_verification', ['verification_uuid'], ['verification_uuid'], ondelete='CASCADE')
    op.drop_column('u_user_npi', 'npi_uuid')
    op.drop_index('ix_u_user_verification_user_uuid', table_name='u_user_verification')
    op.create_index(op.f('ix_u_user_verification_user_uuid'), 'u_user_verification', ['user_uuid'], unique=False)

    update_enum(enum_name='verificationstatus',
                new_values=['ARCHIVED', 'CHANGE_REQUESTED', 'DUPLICATE_NPI', 'INFO_NEEDED', 'LEGACY_UNVERIFIED',
                            'PENDING_MANUAL_VERIFICATION', 'REJECTED', 'REVIEW_REQUIRED', 'UNVERIFIABLE',
                            'UPDATED_INFO',
                            'VERIFIED'],
                column='verification_status',
                table='u_user_verification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum(enum_name='verificationstatus',
                new_values=['DUPLICATE_NPI', 'INFO_NEEDED', 'LEGACY_UNVERIFIED', 'PENDING_MANUAL_VERIFICATION',
                            'UNVERIFIABLE', 'UPDATED_INFO', 'VERIFIED'],
                column='verification_status',
                table='u_user_verification')

    op.drop_index(op.f('ix_u_user_verification_user_uuid'), table_name='u_user_verification')
    op.create_index('ix_u_user_verification_user_uuid', 'u_user_verification', ['user_uuid'], unique=True)
    op.add_column('u_user_npi',
                  sa.Column('npi_uuid', postgresql.UUID(), autoincrement=False, nullable=False,
                            server_default=func.gen_random_uuid()))
    op.drop_constraint(op.f('fk_u_user_npi_verification_uuid_u_user_verification'), 'u_user_npi', type_='foreignkey')
    op.drop_index(op.f('ix_u_user_npi_user_uuid'), table_name='u_user_npi')
    op.create_index('ix_u_user_npi_user_uuid', 'u_user_npi', ['user_uuid'], unique=True)
    op.drop_column('u_user_npi', 'verification_uuid')
    op.add_column('u_user_license', sa.Column('license_uuid', postgresql.UUID(), autoincrement=False, nullable=False,
                                              server_default=func.gen_random_uuid()))
    op.drop_constraint(op.f('fk_u_user_license_verification_uuid_u_user_verification'), 'u_user_license',
                       type_='foreignkey')
    op.drop_index(op.f('ix_u_user_license_user_uuid'), table_name='u_user_license')
    op.create_index('ix_u_user_license_user_uuid', 'u_user_license', ['user_uuid'], unique=True)
    op.drop_column('u_user_license', 'verification_uuid')

    op.drop_constraint(op.f('fk_u_user_verification_change_request_verification_uuid_u_user_verification'),
                       'u_user_verification_change_request', type_='foreignkey')
    op.drop_index(op.f('ix_u_user_verification_change_request_updated_at'),
                  table_name='u_user_verification_change_request')
    op.drop_index(op.f('ix_u_user_verification_change_request_created_at'),
                  table_name='u_user_verification_change_request')
    op.drop_table('u_user_verification_change_request')
    # ### end Alembic commands ###
