"""add mesh term type

Revision ID: 71e12a37476d
Revises: f8f2f5fc179e
Create Date: 2022-03-17 12:35:00.259234

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71e12a37476d'
down_revision = 'f8f2f5fc179e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_case_mesh_terms', sa.Column('mesh_term_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_case_mesh_terms', 'mesh_term_type')
    # ### end Alembic commands ###
