"""flag to track public groups

Revision ID: f4972df84194
Revises: fe2ebc7505e7
Create Date: 2022-09-08 14:31:31.460572

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4972df84194'
down_revision = 'fe2ebc7505e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g_groups', sa.Column('is_public', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('g_groups', 'is_public')
    # ### end Alembic commands ###
