"""add moderator_reviewed to Comment

Revision ID: 1f506847ca83
Revises: 1adbf4367a25
Create Date: 2022-07-27 14:55:55.086250

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f506847ca83'
down_revision = '1adbf4367a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_comment', sa.Column('moderator_reviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_comment', 'moderator_reviewed')
    # ### end Alembic commands ###
