"""Add case classification

Revision ID: cea7a78c19a6
Revises: 32518d77cdca
Create Date: 2022-10-24 11:51:29.796730

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
from figure1.common.utils import create_enum, delete_enum

# revision identifiers, used by Alembic.
revision = 'cea7a78c19a6'
down_revision = '32518d77cdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum(enum_name='caseclassification', values=['MEDICAL', 'NONMEDICAL'])
    op.add_column('c_case',
                  sa.Column('case_classification', sa.Enum('MEDICAL', 'NONMEDICAL', name='caseclassification'),
                            nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_case', 'case_classification')
    delete_enum('caseclassification')
    # ### end Alembic commands ###
