"""reorganize publication tables

Revision ID: a2c213926776
Revises: 64177f3b5d23
Create Date: 2022-02-22 11:31:35.793550

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2c213926776'
down_revision = '64177f3b5d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p_public_publications',
                    sa.Column('pub_med_id', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('pub_med_id', name=op.f('pk_p_public_publications'))
                    )
    op.create_table('c_case_publications',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('case_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('pub_med_id', sa.String(), nullable=True),
                    sa.Column('display_order', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['pub_med_id'], ['p_public_publications.pub_med_id'],
                                            name=op.f('fk_c_case_publications_pub_med_id_p_public_publications')),
                    sa.PrimaryKeyConstraint('case_uuid', 'pub_med_id', name=op.f('pk_c_case_publications'))
                    )
    op.create_index(op.f('ix_c_case_publications_created_at'), 'c_case_publications', ['created_at'], unique=False)
    op.execute(
        """INSERT INTO p_public_publications(pub_med_id, title) 
        SELECT pub_med_id, title from c_publications 
        ON CONFLICT (pub_med_id) DO NOTHING;""")
    op.execute(
        """INSERT INTO c_case_publications(created_at, case_uuid, pub_med_id, display_order) 
        SELECT created_at, case_uuid, pub_med_id, display_order from c_publications where source='CAPTION_TERMS'
        ON CONFLICT (pub_med_id, case_uuid) DO NOTHING;""")

    op.drop_index('ix_c_publications_created_at', table_name='c_publications')
    op.drop_table('c_publications')
    postgresql.ENUM.drop(postgresql.ENUM(name='publication_source'), bind=op.get_bind())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('c_publications',
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
                    sa.Column('pub_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('case_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('pub_med_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('source', postgresql.ENUM('CAPTION_TERMS', 'COMMENT_TERMS', name='publication_source'),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('pub_uuid', name='pk_c_publications')
                    )
    op.create_index('ix_c_publications_created_at', 'c_publications', ['created_at'], unique=False)
    op.execute(
        """INSERT INTO c_publications(created_at, pub_uuid, case_uuid, display_order, pub_med_id) 
        SELECT created_at, gen_random_uuid(), case_uuid, display_order, pub_med_id from c_case_publications 
        ON CONFLICT DO NOTHING;""")
    op.execute("""UPDATE c_publications 
    SET title=ppublic.title from p_public_publications ppublic 
    where ppublic.pub_med_id=c_publications.pub_med_id""")
    op.drop_index(op.f('ix_c_case_publications_created_at'), table_name='c_case_publications')
    op.drop_table('c_case_publications')
    op.drop_table('p_public_publications')
    # ### end Alembic commands ###
