"""Add mesh terms tables

Revision ID: 64177f3b5d23
Revises: 2ead677435d0
Create Date: 2022-02-17 15:50:57.659024

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64177f3b5d23'
down_revision = '2ead677435d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p_public_mesh_concepts',
                    sa.Column('mesh_concept_id', sa.String(), nullable=False),
                    sa.Column('scope_note', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('mesh_concept_id', name=op.f('pk_p_public_mesh_concepts'))
                    )
    op.create_table('p_public_mesh_terms',
                    sa.Column('mesh_term_id', sa.String(), nullable=True),
                    sa.Column('preferred_label', sa.String(), nullable=False),
                    sa.Column('alternate_label', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('mesh_term_id', name=op.f('pk_p_public_mesh_terms'))
                    )
    op.create_table('c_case_mesh_terms',
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('case_uuid', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('mesh_term_id', sa.String(), nullable=False),
                    sa.Column('moderator_uuid', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.ForeignKeyConstraint(['mesh_term_id'], ['p_public_mesh_terms.mesh_term_id'],
                                            name=op.f('fk_c_case_mesh_terms_mesh_term_id_p_public_mesh_terms')),
                    sa.ForeignKeyConstraint(['moderator_uuid'], ['u_user.user_uuid'],
                                            name=op.f('fk_c_case_mesh_terms_moderator_uuid_u_user')),
                    sa.PrimaryKeyConstraint('case_uuid', 'mesh_term_id', name=op.f('pk_c_case_mesh_terms'))
                    )
    op.create_index(op.f('ix_c_case_mesh_terms_created_at'), 'c_case_mesh_terms', ['created_at'], unique=False)
    op.create_index(op.f('ix_c_case_mesh_terms_deleted_at'), 'c_case_mesh_terms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_c_case_mesh_terms_updated_at'), 'c_case_mesh_terms', ['updated_at'], unique=False)
    op.create_table('p_public_mesh',
                    sa.Column('mesh_id', sa.String(), nullable=False),
                    sa.Column('preferredConcept', sa.String(), nullable=True),
                    sa.Column('preferredTerm', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['preferredConcept'], ['p_public_mesh_concepts.mesh_concept_id'],
                                            name=op.f('fk_p_public_mesh_preferredConcept_p_public_mesh_concepts')),
                    sa.ForeignKeyConstraint(['preferredTerm'], ['p_public_mesh_terms.mesh_term_id'],
                                            name=op.f('fk_p_public_mesh_preferredTerm_p_public_mesh_terms')),
                    sa.PrimaryKeyConstraint('mesh_id', name=op.f('pk_p_public_mesh'))
                    )
    op.create_table('p_public_mesh_concept_terms',
                    sa.Column('mesh_concept_id', sa.String(), nullable=False),
                    sa.Column('mesh_term_id', sa.String(), nullable=False),
                    sa.Column('mesh_preferred_term_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['mesh_concept_id'], ['p_public_mesh_concepts.mesh_concept_id'], name=op.f(
                        'fk_p_public_mesh_concept_terms_mesh_concept_id_p_public_mesh_concepts')),
                    sa.ForeignKeyConstraint(['mesh_preferred_term_id'], ['p_public_mesh_terms.mesh_term_id'], name=op.f(
                        'fk_p_public_mesh_concept_terms_mesh_preferred_term_id_p_public_mesh_terms')),
                    sa.ForeignKeyConstraint(['mesh_term_id'], ['p_public_mesh_terms.mesh_term_id'], name=op.f(
                        'fk_p_public_mesh_concept_terms_mesh_term_id_p_public_mesh_terms')),
                    sa.PrimaryKeyConstraint('mesh_concept_id', 'mesh_term_id',
                                            name=op.f('pk_p_public_mesh_concept_terms'))
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('p_public_mesh_concept_terms')
    op.drop_table('p_public_mesh')
    op.drop_index(op.f('ix_c_case_mesh_terms_updated_at'), table_name='c_case_mesh_terms')
    op.drop_index(op.f('ix_c_case_mesh_terms_deleted_at'), table_name='c_case_mesh_terms')
    op.drop_index(op.f('ix_c_case_mesh_terms_created_at'), table_name='c_case_mesh_terms')
    op.drop_table('c_case_mesh_terms')
    op.drop_table('p_public_mesh_terms')
    op.drop_table('p_public_mesh_concepts')
    # ### end Alembic commands ###
