"""make group name unique

Revision ID: b34d970a28aa
Revises: fc9a4217cd33
Create Date: 2022-05-27 13:39:05.996269

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b34d970a28aa'
down_revision = 'fc9a4217cd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_g_groups_group_name'), 'g_groups', ['group_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_g_groups_group_name'), 'g_groups', type_='unique')
    # ### end Alembic commands ###
