"""update onboardingstate enum

Revision ID: 670d44cb4c01
Revises: cd4006c7bb6c
Create Date: 2022-03-30 13:04:34.737535

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '670d44cb4c01'
down_revision = 'cd4006c7bb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE onboardingstate ADD VALUE 'GRAD_DATE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE u_user_state SET onboarding_state = NULL WHERE onboarding_state = 'GRAD_DATE'")
    op.execute("ALTER TYPE onboardingstate RENAME TO onboardingstate_tmp")
    op.execute("CREATE TYPE onboardingstate AS ENUM('COMPLETED', 'COUNTRY', 'INFORMATION', 'USA_INFORMATION', 'USERNAME', 'VERIFICATION')")
    op.execute("ALTER TABLE u_user_state ALTER COLUMN onboarding_state TYPE onboardingstate USING onboarding_state::text::onboardingstate")
    op.execute("DROP TYPE onboardingstate_tmp")
# ### end Alembic commands ###
