"""add group_uuid to n_user_notification and update usernotificationtype

Revision ID: b4dd93c348eb
Revises: b43516089106
Create Date: 2022-03-28 10:13:30.390930

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
from figure1.common.utils import update_enum
# revision identifiers, used by Alembic.


revision = 'b4dd93c348eb'
down_revision = 'b43516089106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('n_user_notification', sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_n_user_notification_group_uuid_g_groups'), 'n_user_notification', 'g_groups', ['group_uuid'], ['group_uuid'])
    op.sync_enum_values('public', 'usernotificationtype', ['APPROVE', 'CASE_DELETE', 'COMMENT', 'COMMENT_DELETE', 'COMMENT_REPLY', 'COMMENT_REPLY_OP', 'COMMENT_SAVED_CASE', 'COMMENT_SAVED_CASE_OP', 'MODERATION_ACTIVITY', 'NEW_CASE_FOLLOWED_USER', 'NEW_CASE_USER_SAVED_CASE', 'NEW_FOLLOWER', 'PAGING', 'REACT', 'REJECT', 'SAVED_CASE_UPDATE'], ['APPROVE', 'CASE_DELETE', 'COMMENT', 'COMMENT_DELETE', 'COMMENT_REPLY', 'COMMENT_REPLY_OP', 'COMMENT_SAVED_CASE', 'COMMENT_SAVED_CASE_OP', 'NEW_CASE_FOLLOWED_USER', 'NEW_CASE_GROUP', 'NEW_CASE_USER_SAVED_CASE', 'NEW_FOLLOWER', 'PAGING', 'REACT', 'REJECT', 'SAVED_CASE_UPDATE'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE', 'CASE_DELETE', 'COMMENT', 'COMMENT_DELETE', 'COMMENT_REPLY', 'COMMENT_REPLY_OP', 'COMMENT_SAVED_CASE', 'COMMENT_SAVED_CASE_OP', 'MODERATION_ACTIVITY', 'NEW_CASE_FOLLOWED_USER', 'NEW_CASE_USER_SAVED_CASE', 'NEW_FOLLOWER', 'PAGING', 'REACT', 'REJECT', 'SAVED_CASE_UPDATE'],
                'n_user_notification',
                'notification_type',
                {'NEW_CASE_GROUP': 'NULL'})
    op.drop_constraint(op.f('fk_n_user_notification_group_uuid_g_groups'), 'n_user_notification', type_='foreignkey')
    op.drop_column('n_user_notification', 'group_uuid')
    # ### end Alembic commands ###
