"""Remove mesh uuid column
Revision ID: b1cc6c12ffad
Revises: 3690c966b448
Create Date: 2022-02-28 16:14:50.906049

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1cc6c12ffad'
down_revision = '3690c966b448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('c_mesh_terms', 'mesh_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_mesh_terms', sa.Column('mesh_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
