"""Add profession tree uuid column

Revision ID: fe9d29a7cf7c
Revises: 21ff0ee696cf
Create Date: 2022-05-16 16:59:22.696096

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe9d29a7cf7c'
down_revision = '21ff0ee696cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_user_verification',
                  sa.Column('profession_tree_uuid', postgresql.UUID(as_uuid=True), nullable=True))


def downgrade():
    op.drop_column('u_user_verification', 'profession_tree_uuid')

