"""Add change request columns

Revision ID: f7d161683d43
Revises: 655635605cd0
Create Date: 2022-04-25 13:20:36.959889

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7d161683d43'
down_revision = '655635605cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_user_verification_change_request',
                  sa.Column('archived_verification_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('u_user_verification_change_request', sa.Column('request_resolved', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('u_user_verification_change_request', 'request_resolved')
    op.drop_column('u_user_verification_change_request', 'archived_verification_uuid')
