"""update usernotificationtype

Revision ID: b22acb329286
Revises: 1f506847ca83
Create Date: 2022-08-17 14:58:20.740554

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from figure1.common.utils import update_enum

revision = 'b22acb329286'
down_revision = '1f506847ca83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN',
                 'COMMENT',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'GROUP_INVITE_ACCEPTED',
                 'LIKED_CASE_DIAGNOSIS',
                 'NEW_ACCEPTED_ANSWER_COMMENTED_CASE',
                 'NEW_ACCEPTED_ANSWER_LIKED_CASE',
                 'NEW_ACCEPTED_ANSWER_SAVED_CASE',
                 'NEW_ACCEPTED_ANSWER_SELECTED',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'PROFESSION_CHANGE_APPROVED',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_DIAGNOSIS',
                 'SAVED_CASE_UPDATE'],
                'n_user_notification',
                'notification_type',
                {}
                )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN',
                 'COMMENT',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'GROUP_INVITE_ACCEPTED',
                 'LIKED_CASE_DIAGNOSIS',
                 'MODERATION_ACTIVITY',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'PROFESSION_CHANGE_APPROVED',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_DIAGNOSIS',
                 'SAVED_CASE_UPDATE'],
                'n_user_notification',
                'notification_type',
                {}
                )
    # ### end Alembic commands ###
