"""update usernotificationtype

Revision ID: bec8dace04bd
Revises: f4972df84194
Create Date: 2022-09-20 10:32:26.491414

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from figure1.common.utils import update_enum

revision = 'bec8dace04bd'
down_revision = 'f4972df84194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN',
                 'COMMENT',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'GROUP_INVITE_ACCEPTED',
                 'LIKED_CASE_DIAGNOSIS',
                 'NEW_ACCEPTED_ANSWER_COMMENTED_CASE',
                 'NEW_ACCEPTED_ANSWER_LIKED_CASE',
                 'NEW_ACCEPTED_ANSWER_SAVED_CASE',
                 'NEW_ACCEPTED_ANSWER_SELECTED',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'PROFESSION_CHANGE_APPROVED',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_DIAGNOSIS',
                 'SAVED_CASE_UPDATE',
                 'ACCEPTED_ANSWER_DELETED'],
                'n_user_notification',
                'notification_type',
                {}
                )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('usernotificationtype',
                ['APPROVE',
                 'CASE_DELETE',
                 'CASE_NOT_DIAGNOSIS_CHOSEN',
                 'COMMENT',
                 'COMMENTED_CASE_DIAGNOSIS',
                 'COMMENT_DELETE',
                 'COMMENT_REPLY',
                 'COMMENT_REPLY_OP',
                 'COMMENT_SAVED_CASE',
                 'COMMENT_SAVED_CASE_OP',
                 'GROUP_INVITE_ACCEPTED',
                 'LIKED_CASE_DIAGNOSIS',
                 'NEW_ACCEPTED_ANSWER_COMMENTED_CASE',
                 'NEW_ACCEPTED_ANSWER_LIKED_CASE',
                 'NEW_ACCEPTED_ANSWER_SAVED_CASE',
                 'NEW_ACCEPTED_ANSWER_SELECTED',
                 'NEW_CASE_FOLLOWED_USER',
                 'NEW_CASE_GROUP',
                 'NEW_CASE_USER_SAVED_CASE',
                 'NEW_FOLLOWER',
                 'PAGING',
                 'PROFESSION_CHANGE_APPROVED',
                 'REACT',
                 'REJECT',
                 'SAVED_CASE_DIAGNOSIS',
                 'SAVED_CASE_UPDATE'],
                'n_user_notification',
                'notification_type',
                {}
                )
    # ### end Alembic commands ###
