"""Add group avatar column

Revision ID: 61b197dbabbc
Revises: ec508fff0093
Create Date: 2022-01-24 10:10:43.558610

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61b197dbabbc'
down_revision = 'ec508fff0093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('g_groups', sa.Column('group_avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('g_groups', 'group_avatar')
    # ### end Alembic commands ###
