"""update usernotificationstate

Revision ID: fe2ebc7505e7
Revises: b22acb329286
Create Date: 2022-08-22 14:54:05.540809

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from figure1.common.utils import update_enum

revision = 'fe2ebc7505e7'
down_revision = 'b22acb329286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum(
        'usernotificationstate',
        ['ACKNOWLEDGED', 'NEW', 'READ'],
        'n_user_notification',
        'state',
        {}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum(
        'usernotificationstate',
        ['ACKNOWLEDGED', 'NEW'],
        'n_user_notification',
        'state',
        {}
    )
    # ### end Alembic commands ###
