"""Add new onboarding value

Revision ID: 70d03465c5e3
Revises: b62cfc3816bc
Create Date: 2022-10-12 16:01:32.109204

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
from figure1.common.utils import update_enum

# revision identifiers, used by Alembic.
revision = '70d03465c5e3'
down_revision = 'b62cfc3816bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    update_enum('onboardingstate',
                ['COMPLETED',
                 'COUNTRY',
                 'GRAD_DATE',
                 'CONFIRMATION',
                 'INFORMATION',
                 'USA_INFORMATION',
                 'USERNAME',
                 'VERIFICATION'],
                'u_user_state',
                'onboarding_state',
                {}
                )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_enum('onboardingstate',
                ['COMPLETED',
                 'COUNTRY',
                 'GRAD_DATE',
                 'INFORMATION',
                 'USA_INFORMATION',
                 'USERNAME',
                 'VERIFICATION'],
                'u_user_state',
                'onboarding_state',
                {}
                )

    # ### end Alembic commands ###
