"""add_group_uuid_to_case

Revision ID: 0d5d43500318
Revises: 3bdb43587fae
Create Date: 2022-01-06 21:12:20.991586

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d5d43500318'
down_revision = '3bdb43587fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_case', sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_c_case_group_uuid_g_groups'), 'c_case', 'g_groups', ['group_uuid'], ['group_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_c_case_group_uuid_g_groups'), 'c_case', type_='foreignkey')
    op.drop_column('c_case', 'group_uuid')
    # ### end Alembic commands ###
