"""add group type to groups

Revision ID: 72c002cd51af
Revises: 2b78a36bf757
Create Date: 2022-05-02 11:33:37.005309

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72c002cd51af'
down_revision = '2b78a36bf757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    grouptype = postgresql.ENUM('INSTITUTIONAL', 'USER', name='grouptype')
    grouptype.create(op.get_bind())
    op.add_column('g_groups',
                  sa.Column('group_type',
                            sa.Enum('INSTITUTIONAL', 'USER', name='grouptype'),
                            nullable=False, server_default='INSTITUTIONAL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###resql.UUID(),
    op.drop_column('g_groups', 'group_type')
    op.execute(f'DROP TYPE grouptype')
    # ### end Alembic commands ###
