"""add diagnosis support

Revision ID: dea82859dacf
Revises: f060772b509c
Create Date: 2022-03-30 23:24:31.030424

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dea82859dacf'
down_revision = 'f060772b509c'
branch_labels = None
depends_on = None


def upgrade():
    contentupdatetype = postgresql.ENUM('UPDATE', 'DIAGNOSIS', name='contentupdatetype')
    contentupdatetype.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_content_update', sa.Column('update_type', sa.Enum('DIAGNOSIS', 'UPDATE', name='contentupdatetype'),
                                                nullable=False, server_default='UPDATE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('c_content_update', 'update_type')
    # ### end Alembic commands ###
