"""add dmd_npi_info table

Revision ID: c1d75a1d03a3
Revises: 993f6ed0281e
Create Date: 2022-11-27 17:29:22.642957

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1d75a1d03a3'
down_revision = '993f6ed0281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_dmd_npi_info',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('npi_number', sa.BigInteger(), nullable=True),
    sa.Column('profession', sa.Text(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('subspecialty', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('practice_hospital', sa.Text(), nullable=True),
    sa.Column('practice_location', sa.Text(), nullable=True),
    sa.Column('graduation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school', sa.Text(), nullable=True),
    sa.Column('dmd_hcp_type', sa.Text(), nullable=True),
    sa.Column('dmd_dgid', sa.Text(), nullable=True),
    sa.Column('dmd_firstname', sa.Text(), nullable=True),
    sa.Column('dmd_lastname', sa.Text(), nullable=True),
    sa.Column('dmd_degree', sa.Text(), nullable=True),
    sa.Column('dmd_primary_specialty', sa.Text(), nullable=True),
    sa.Column('dmd_specialty_long_description', sa.Text(), nullable=True),
    sa.Column('dmd_npi', sa.BigInteger(), nullable=True),
    sa.Column('dmd_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_uuid', name=op.f('pk_v_dmd_npi_info'))
    )

    op.create_index(op.f('ix_v_dmd_npi_info_email'), 'v_dmd_npi_info', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v_dmd_npi_info_email'), table_name='v_dmd_npi_info')
    op.drop_table('v_dmd_npi_info')
    # ### end Alembic commands ###
