import logging
import os
from pydantic.env_settings import SettingsSourceCallable
from pydantic import BaseSettings
from pydantic import Extra
from pydantic import Field
from pydantic import validator
from pydantic import ValidationError
from pydantic import HttpUrl
from pydantic import PostgresDsn
from pydantic import SecretStr
from pydantic import AnyUrl
from pydantic import FilePath
from typing import Literal, Optional
from typing import List
from typing import Union


class MobileUrl(AnyUrl):
    allowed_schemes = {'figure1pro'}


class RedisSentinel(AnyUrl):
    allowed_schemes = {'redis', 'sentinel'}


class ElasticSearchSettings(BaseSettings):
    hosts: str = "http://elasticsearch:9200"
    cloud_id: Optional[str]
    api_key: Optional[str]
    connect_retry_count: int = 10
    connect_retry_wait: int = 10
    legacy_cases_alias: str = "legacycases"
    cases_alias: str = "newcases"
    comments_alias: str = "comments"
    users_alias: str = "users"
    campaign_alias: str = "campaigns"
    groups_alias: str = 'groups'
    public_search_terms_alias: str = "public_search_terms"
    public_search_terms_alias_v2: str = "public_search_terms_v2"
    public_specialty_alias: str = "public_specialty"
    public_schools_alias: str = "public_schools"
    public_countries_alias: str = "public_countries"
    # public_feed_states indicates what state in required to show up in search results or in any of the feeds
    # public_read_permitted may not show up in feeds, but may be accessed if a link is available, or in sponsored
    # content.
    public_feed_states: List[str] = ["APPROVED"]
    public_read_permitted: List[str] = ["APPROVED", "SC_APPROVED", "SC_REVIEW"]

    class Config:
        env_prefix = 'elasticsearch_'


class FirebaseEnvSettings(BaseSettings):
    client_x509_cert_url: str
    client_id: str
    client_email: str
    private_key: str
    private_key_id: str
    project_id: str
    rtdb_url: Optional[str]
    firestore_emulator_host: Optional[str]

    class Config:
        env_prefix = 'firebase_'
        extra = Extra.ignore

    @validator('private_key', pre=True)
    def parse_key(cls, v: str):
        return v.replace(r"\n", "\n").strip('"')

class AppSettings(BaseSettings):
    """
    Logging Level:
    There are 4 distinct places where log level can be set, each is independent of the others. Each one can be set
    with one of the standard log levels ( CRITICAL, ERROR, WARNING, INFO, DEBUG ). The elasticsearch and sqlalchemy
    loggers default to ERROR level, the other two default to INFO level logging.


    :log_level: handles the figure1.* loggers, for the most part, these are messages that are generated by the
    figure1 api.

    :log_level_sqlalchemy: handles the logging generated by sql alchemy, setting this higher than info will generate a
    substantial amount of logs, but it can be useful.

    :log_level_elasticsearch: handles elasticsearch searches and updates

    :log_level_gunicorn: Gunicorn handles serving the wsgi app, setting this to debug shows the access logs, higher than
    this does not show access logs, but shows other gunicorn events.

    Logging Targets

    There are two targets configured by default, the console writes to stdout, and the file target writes to a rotating
    file handler.
    For the file handler, there is a path for the api logs, and a separate one for worker logs. The paths here are
    checked for write permission on startup, if it isn't possible to write to the log file, the handler is disabled.

    Both the console and the log file targets can be enabled or disabled.

    :threshold_forbidden_usernames: usernames that must not be allowed even when part of a larger word

    :threshold_forbidden_usernames: usernames are only allowed when part of a larger word

    :test_mode: In most cases, this skips attempts at external calls. It also attempts to run any tasks synchronously
    where possible.

    :read_only_dev_mode: Enables read-only mode that prevents all write operations including database commits, 
    external API calls, S3 uploads, Firestore writes, and Elasticsearch indexing. Useful for maintenance mode 
    and safe development/testing against production data.

    """
    log_level: str = 'INFO'
    log_level_sqlalchemy: str = 'ERROR'
    log_level_elasticsearch: str = 'ERROR'
    log_level_gunicorn: str = 'INFO'
    console_log_enabled: bool = True
    app_url: HttpUrl = "https://app.figure1.com"
    external_webapp_url: HttpUrl = "https://app.figure1.com"
    login_link_default_continue_path: Optional[str] = "/accept-login-link"
    external_mobileapp_url: MobileUrl = "figure1pro://app.figure1.com"
    external_marketing_url: HttpUrl = "https://www.figure1.com"
    case_cme_template: Optional[str] = "cases/certificate-templates/case-cme/medchi-physician.docx"
    case_cme_enabled: bool = False
    case_sync_enabled: bool = False
    case_state_event_listener_enabled: bool = True
    case_sync_throttle: int = 30
    case_sync_throttle_enabled: bool = False
    db_host: Optional[str] = 'figure1-database'
    db_port: Optional[int] = 30001
    db_database: Optional[str] = 'figure1'
    db_username: Optional[str] = 'figure1_admin'
    db_password: Optional[SecretStr] = 'test1234'
    database_dsn: Optional[PostgresDsn]
    feed_throttle_seconds: int = 3
    feed_preview_new_enabled: bool = True
    feed_preview_new_location: int = 2
    feed_preview_trending_enabled: bool = True
    feed_preview_trending_location: int = 5
    feed_rfy_v2_enabled: bool = True
    feed_rfy_history_filter: bool = False
    feed_rfy_history_expire: int = 604800
    feed_rfy_views_expire: int = 604800
    feed_rfy_new_items_expire: int = 604800
    feed_rfy_expire: int = 604800
    figure1_imgix_url: HttpUrl = "https://figure1-pro-prod.imgix.net/"
    iterable_android_env_name: Optional[str]
    iterable_api_key: Optional[str]
    iterable_base_url: HttpUrl = "https://api.iterable.com"
    iterable_ios_env_name: Optional[str]
    iterable_web_env_name: Optional[str]
    iterable_reset_password_campaign_id: Optional[int]
    iterable_contact_support_campaign_id: Optional[int]
    iterable_login_link_campaign_id: Optional[int]
    iterable_invite_colleagues_campaign_id: Optional[int]
    iterable_invite_group_members_campaign_id: Optional[int]
    legacy_backdoor: Optional[str]
    mesh_api_url: HttpUrl = "https://meshb.nlm.nih.gov/api/MOD"
    mesh_execution_environment = "dev"
    mesh_max_attempts: int = 4
    mesh_api_enabled: bool = True
    mixpanel_api_key: Optional[str]
    sentinel_enabled: bool = False
    redis_url: Union[List[RedisSentinel], RedisSentinel] = "redis://redis:6379"
    s3_upload_bucket: Optional[str]
    slack_channel_moderation_notifications: Optional[str]
    slack_channel_group_moderation_notifications: Optional[str]
    slack_channel_verification_notifications: Optional[str]
    slack_enabled: bool = False
    slack_username: str = "Notification Bot"
    slack_webhook_url: Optional[str]
    sponsored_content_enabled: bool = True
    sponsored_content_queue_generation_delay: int = 86400
    translation_api_enabled: bool = False
    test_mode: bool = False
    read_only_dev_mode: Optional[bool] = False
    user_sync_enabled: bool = False
    verification_event_listener_enabled: bool = True
    vimeo_client_id: Optional[str]
    vimeo_secret: Optional[str]
    vimeo_token: Optional[str]
    threshold_forbidden_usernames: int = 86
    threshold_less_forbidden_usernames: int = 92

    @validator('log_level', 'log_level_sqlalchemy', 'log_level_elasticsearch', 'log_level_gunicorn')
    def validate_log_level(cls, value):
        if isinstance(value, str):
            log_level = logging.getLevelName(value.upper())
            if log_level == f'Level {value}':
                return logging.INFO
            else:
                return log_level
        return logging.INFO

    @validator('redis_url', pre=True)
    def handle_redis_url(cls, value):
        if value:
            sentinels = []
            for v in value.split(';'):
                sentinels.append(v.strip(';'))
            if len(sentinels) == 1:
                return value
            return sentinels
        return value

    def generate_default_login_link(self):
        return f"{self.app_url}{self.login_link_default_continue_path}"


class FlaskSettings(BaseSettings):
    upload_max_content_length: int = 10 * 1024 * 1024
    upload_temp_dir: str = '/tmp'
    jwt_secret_key: str = Field(default="supersecret")
    jwt_auth_url_rule: str = '/api/auth'
    firebase_environment: str = 'firebase-admin-dev'
    flask_mode: str = Field(pattern=r'^debug|testing$', default=None)
    read_only_dev_mode: Optional[bool] = False

class TestSettings(BaseSettings):
    """
    Settings for running tests
    :test_migrations: Whether migrations should be run or not. This can cover some bugs, but can also prevent others
        from being exposed.
    """
    migrations: bool = False

    class Config:
        env_prefix = 'test_'
